import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'en' | 'dar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Header
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.ai': 'IA & Humain',
    'nav.testimonials': 'Témoignages',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.title': 'Convertir sans forcer. Performer avec conscience.',
    'hero.subtitle': "L'alliance entre psychologie, IA et éthique pour une vente augmentée.",
    'hero.cta.primary': 'Découvrir notre approche',
    'hero.cta.secondary': 'Réserver un audit gratuit',
    
    // Mission
    'mission.title': "L'éthique comme stratégie.",
    'mission.text': "Chez The Ultimate Closers, chaque conversion est une conversation honnête. L'IA amplifie la compréhension, jamais la manipulation.",
    'mission.value1': 'Bienveillance',
    'mission.value2': 'Transparence',
    'mission.value3': 'Souveraineté',
    'mission.value4': 'Excellence',
    
    // Services
    'services.title': 'Des solutions humaines, soutenues par la technologie.',
    'services.card1.title': 'Closing à la performance',
    'services.card1.text': 'Payez uniquement quand vous signez.',
    'services.card2.title': 'Coaching & Scripts',
    'services.card2.text': 'Vente consciente et éthique.',
    'services.card3.title': 'Audit Funnel & IA',
    'services.card3.text': 'Analyse comportementale & automatisation.',
    'services.card4.title': 'Automatisation IA Darija',
    'services.card4.text': 'Une IA formée à votre culture.',
    
    // AI
    'ai.title': 'Une intelligence locale au service de votre croissance.',
    'ai.text': 'Notre IA Darija comprend vos émotions, votre culture et vos valeurs.',
    'ai.feature1': 'Chatbot empathique',
    'ai.feature2': 'CRM intelligent',
    'ai.feature3': 'LLM culturel',
    
    // Results
    'results.title': 'Des résultats mesurables, une éthique non négociable.',
    'results.metric1': '+70 % de taux de closing',
    'results.metric2': '0 % de forcing',
    'results.metric3': '100 % de satisfaction client',
    'results.quote': "L'éthique n'est pas un frein à la performance, c'est son fondement.",
    'results.author': 'A. Maredj',
    
    // Testimonials
    'testimonials.title': 'Ils nous ont fait confiance.',
    'testimonials.card1': "J'ai signé deux fois plus sans me sentir commerciale.",
    'testimonials.card2': 'They made my process human and efficient.',
    'testimonials.card3': 'خدمتهم راقية و فيها نية.',
    'testimonials.name1': 'Sofia',
    'testimonials.name2': 'Marc',
    'testimonials.name3': 'Yasmine',
    
    // CTA
    'cta.title': 'Prêt à transformer votre manière de vendre ?',
    'cta.button': 'Réserver un audit gratuit',
    
    // Footer
    'footer.quote': 'La sagesse dans la vente, la lumière dans la croissance.',
    'footer.legal': 'Mentions légales',
    
    // Booking
    'booking.back': 'Retour à l\'accueil',
    'booking.step1.title': 'Réservez votre appel stratégique',
    'booking.step1.subtitle': 'Cet appel découverte est conçu pour évaluer si nos systèmes d\'acquisition éthique et automatisée peuvent s\'intégrer à votre modèle.',
    'booking.step1.what': 'Ce qui vous attend',
    'booking.step1.item1': 'Une analyse personnalisée de votre processus commercial actuel',
    'booking.step1.item2': 'Des stratégies concrètes pour automatiser votre prospection',
    'booking.step1.item3': 'L\'évaluation de la compatibilité entre nos systèmes et vos objectifs',
    'booking.step1.important': 'Important :',
    'booking.step1.notice': 'Cet appel n\'est pas un conseil gratuit. C\'est une évaluation mutuelle réservée aux dirigeants et responsables commerciaux décidés à scaler leurs ventes. Merci de répondre avec précision pour qu\'on prépare une analyse personnalisée.',
    'booking.step1.button': 'Commencer le formulaire',
    'booking.step2.title': 'Qui êtes-vous ?',
    'booking.step2.subtitle': 'Commençons par faire connaissance',
    'booking.step2.firstName': 'Prénom',
    'booking.step2.lastName': 'Nom',
    'booking.step2.jobTitle': 'Poste occupé',
    'booking.step2.companyName': 'Nom de l\'entreprise',
    'booking.step2.companyWebsite': 'Site web de l\'entreprise',
    'booking.step2.companyLinkedin': 'Page LinkedIn',
    'booking.step2.email': 'Email professionnel',
    'booking.step2.phone': 'Téléphone / WhatsApp',
    'booking.step3.title': 'Votre entreprise',
    'booking.step3.subtitle': 'Aidez-nous à comprendre votre contexte',
    'booking.step3.industry': 'Secteur d\'activité',
    'booking.step3.revenue': 'Chiffre d\'affaires annuel',
    'booking.step3.teamSize': 'Taille de l\'équipe commerciale',
    'booking.step3.channels': 'Canaux actuels d\'acquisition',
    'booking.step3.challenge': 'Quel est votre principal défi actuellement ?',
    'booking.step4.title': 'Vos objectifs',
    'booking.step4.subtitle': 'Qu\'attendez-vous de cet appel ?',
    'booking.step4.objective': 'Qu\'espérez-vous obtenir de cet appel ?',
    'booking.step4.automate': 'Automatiser la prospection',
    'booking.step4.automate.desc': 'Mettre en place des systèmes d\'acquisition automatisés',
    'booking.step4.train': 'Former mes closers',
    'booking.step4.train.desc': 'Améliorer les compétences de mon équipe commerciale',
    'booking.step4.rethink': 'Repenser le pipeline',
    'booking.step4.rethink.desc': 'Optimiser l\'ensemble du processus de vente',
    'booking.step4.other': 'Autre objectif',
    'booking.step4.other.desc': 'Je veux discuter d\'un besoin spécifique',
    'booking.step4.aiCrm': 'Avez-vous déjà utilisé un système de closing assisté par IA ou CRM automatisé ?',
    'booking.step4.aiCrm.yes': 'Oui, j\'utilise ou ai utilisé ces outils',
    'booking.step4.aiCrm.no': 'Non, pas encore',
    'booking.step4.aiCrm.progress': 'En cours de mise en place',
    'booking.step4.urgency': 'Quelle est votre urgence à agir ?',
    'booking.step4.urgency.week': 'Cette semaine',
    'booking.step4.urgency.month': 'Dans le mois',
    'booking.step4.urgency.not': 'Pas prioritaire pour le moment',
    'booking.step5.title': 'Planification',
    'booking.step5.subtitle': 'Choisissez votre créneau préféré',
    'booking.step5.date': 'Date préférée',
    'booking.step5.timezone': 'Fuseau horaire',
    'booking.step5.platform': 'Plateforme préférée',
    'booking.step5.platformQuestion': 'Comment souhaitez-vous nous rejoindre ?',
    'booking.step5.notice': 'Après validation, vous recevrez un email de confirmation avec le lien de l\'appel et la possibilité d\'ajouter l\'événement à votre calendrier.',
    'booking.step6.title': 'Dernière étape',
    'booking.step6.subtitle': 'Confirmez votre engagement',
    'booking.step6.warning': 'Cet appel est réservé aux professionnels sérieux',
    'booking.step6.intro': 'Cet appel découverte est conçu pour les dirigeants et responsables commerciaux décidés à scaler leurs ventes. Nous investissons du temps dans la préparation d\'une analyse personnalisée pour chaque prospect.',
    'booking.step6.not': 'Cet appel N\'EST PAS pour vous si :',
    'booking.step6.not1': 'Vous cherchez uniquement un conseil gratuit',
    'booking.step6.not2': 'Vous n\'êtes pas décisionnaire dans votre entreprise',
    'booking.step6.not3': 'Vous n\'avez pas de budget pour investir dans votre croissance',
    'booking.step6.not4': 'Vous n\'êtes pas sûr de pouvoir être présent',
    'booking.step6.is': 'Cet appel EST pour vous si :',
    'booking.step6.is1': 'Vous voulez automatiser votre acquisition de clients',
    'booking.step6.is2': 'Vous êtes prêt à investir pour scaler votre business',
    'booking.step6.is3': 'Vous cherchez une solution éprouvée, pas des théories',
    'booking.step6.is4': 'Vous êtes décideur et prêt à agir rapidement',
    'booking.step6.confirm': 'Je confirme mon engagement',
    'booking.step6.confirmText': 'Je comprends que cet appel est une évaluation mutuelle et je m\'engage à être présent à l\'heure prévue. Je suis décisionnaire et prêt à investir dans la croissance de mon entreprise.',
    'booking.step6.submit': 'Confirmer ma réservation',
    'booking.step6.submitting': 'Envoi en cours...',
    'booking.step7.success': 'Réservation confirmée !',
    'booking.step7.thanks': 'Merci',
    'booking.step7.message': 'Votre demande d\'appel a bien été enregistrée. Vous allez recevoir un email de confirmation sous peu.',
    'booking.step7.details': 'Détails de votre réservation :',
    'booking.step7.date': 'Date préférée :',
    'booking.step7.email': 'Email :',
    'booking.step7.company': 'Entreprise :',
    'booking.step7.next': 'Prochaines étapes',
    'booking.step7.next1': 'Nous allons analyser votre profil et vos besoins',
    'booking.step7.next2': 'Vous recevrez un email de confirmation avec le lien de l\'appel',
    'booking.step7.next3': 'Nous préparerons une analyse personnalisée pour votre entreprise',
    'booking.step7.home': 'Retour à l\'accueil',
    'booking.button.back': 'Retour',
    'booking.button.continue': 'Continuer',
    'booking.channel.inbound': 'Inbound Marketing',
    'booking.channel.outbound': 'Outbound / Cold Calling',
    'booking.channel.ads': 'Publicité payante',
    'booking.channel.referral': 'Recommandations',
    'booking.channel.other': 'Autre',
    'booking.select': 'Sélectionnez',
    'booking.urgent': 'Urgent',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.ai': 'AI & Human',
    'nav.testimonials': 'Testimonials',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.title': 'Convert without pressure. Perform with conscience.',
    'hero.subtitle': 'Merging psychology, AI, and ethics to reinvent selling.',
    'hero.cta.primary': 'Discover our approach',
    'hero.cta.secondary': 'Book your free audit',
    
    // Mission
    'mission.title': 'Ethics as strategy.',
    'mission.text': 'At The Ultimate Closers, every conversion is an honest conversation. AI amplifies understanding, never manipulation.',
    'mission.value1': 'Benevolence',
    'mission.value2': 'Transparency',
    'mission.value3': 'Sovereignty',
    'mission.value4': 'Excellence',
    
    // Services
    'services.title': 'Human solutions, powered by technology.',
    'services.card1.title': 'Performance-based closing',
    'services.card1.text': 'Pay only when you sign.',
    'services.card2.title': 'Coaching & Scripts',
    'services.card2.text': 'Conscious and ethical selling.',
    'services.card3.title': 'Funnel & AI Audit',
    'services.card3.text': 'Behavioral analysis & automation.',
    'services.card4.title': 'Darija AI Automation',
    'services.card4.text': 'An AI trained on your culture.',
    
    // AI
    'ai.title': 'Local intelligence serving your growth.',
    'ai.text': 'Our Darija AI understands your emotions, culture, and values.',
    'ai.feature1': 'Empathetic chatbot',
    'ai.feature2': 'Smart CRM',
    'ai.feature3': 'Cultural LLM',
    
    // Results
    'results.title': 'Measurable results, non-negotiable ethics.',
    'results.metric1': '+70% closing rate',
    'results.metric2': '0% pressure',
    'results.metric3': '100% client satisfaction',
    'results.quote': 'Ethics is not a barrier to performance, it is its foundation.',
    'results.author': 'A. Maredj',
    
    // Testimonials
    'testimonials.title': 'They trusted us.',
    'testimonials.card1': 'I signed twice as much without feeling pushy.',
    'testimonials.card2': 'They made my process human and efficient.',
    'testimonials.card3': 'Their service is premium and intentional.',
    'testimonials.name1': 'Sofia',
    'testimonials.name2': 'Marc',
    'testimonials.name3': 'Yasmine',
    
    // CTA
    'cta.title': 'Ready to transform the way you sell?',
    'cta.button': 'Book your free audit',
    
    // Footer
    'footer.quote': 'Wisdom in sales, light in growth.',
    'footer.legal': 'Legal',
    
    // Booking
    'booking.back': 'Back to home',
    'booking.step1.title': 'Book your strategic call',
    'booking.step1.subtitle': 'This discovery call is designed to assess if our ethical and automated acquisition systems can integrate with your model.',
    'booking.step1.what': 'What to expect',
    'booking.step1.item1': 'A personalized analysis of your current sales process',
    'booking.step1.item2': 'Concrete strategies to automate your prospecting',
    'booking.step1.item3': 'Evaluation of compatibility between our systems and your goals',
    'booking.step1.important': 'Important:',
    'booking.step1.notice': 'This call is not free advice. It\'s a mutual evaluation reserved for executives and sales managers committed to scaling their sales. Please respond accurately so we can prepare a personalized analysis.',
    'booking.step1.button': 'Start the form',
    'booking.step2.title': 'Who are you?',
    'booking.step2.subtitle': 'Let\'s get to know each other',
    'booking.step2.firstName': 'First name',
    'booking.step2.lastName': 'Last name',
    'booking.step2.jobTitle': 'Job title',
    'booking.step2.companyName': 'Company name',
    'booking.step2.companyWebsite': 'Company website',
    'booking.step2.companyLinkedin': 'LinkedIn page',
    'booking.step2.email': 'Professional email',
    'booking.step2.phone': 'Phone / WhatsApp',
    'booking.step3.title': 'Your company',
    'booking.step3.subtitle': 'Help us understand your context',
    'booking.step3.industry': 'Industry',
    'booking.step3.revenue': 'Annual revenue',
    'booking.step3.teamSize': 'Sales team size',
    'booking.step3.channels': 'Current acquisition channels',
    'booking.step3.challenge': 'What is your main challenge currently?',
    'booking.step4.title': 'Your goals',
    'booking.step4.subtitle': 'What do you expect from this call?',
    'booking.step4.objective': 'What do you hope to get from this call?',
    'booking.step4.automate': 'Automate prospecting',
    'booking.step4.automate.desc': 'Implement automated acquisition systems',
    'booking.step4.train': 'Train my closers',
    'booking.step4.train.desc': 'Improve my sales team skills',
    'booking.step4.rethink': 'Rethink the pipeline',
    'booking.step4.rethink.desc': 'Optimize the entire sales process',
    'booking.step4.other': 'Other objective',
    'booking.step4.other.desc': 'I want to discuss a specific need',
    'booking.step4.aiCrm': 'Have you used an AI-assisted closing system or automated CRM?',
    'booking.step4.aiCrm.yes': 'Yes, I use or have used these tools',
    'booking.step4.aiCrm.no': 'No, not yet',
    'booking.step4.aiCrm.progress': 'Implementation in progress',
    'booking.step4.urgency': 'How urgent is your need to act?',
    'booking.step4.urgency.week': 'This week',
    'booking.step4.urgency.month': 'Within the month',
    'booking.step4.urgency.not': 'Not a priority right now',
    'booking.step5.title': 'Scheduling',
    'booking.step5.subtitle': 'Choose your preferred time slot',
    'booking.step5.date': 'Preferred date',
    'booking.step5.timezone': 'Timezone',
    'booking.step5.platform': 'Preferred platform',
    'booking.step5.platformQuestion': 'How would you like to join us?',
    'booking.step5.notice': 'After validation, you will receive a confirmation email with the call link and the option to add the event to your calendar.',
    'booking.step6.title': 'Final step',
    'booking.step6.subtitle': 'Confirm your commitment',
    'booking.step6.warning': 'This call is reserved for serious professionals',
    'booking.step6.intro': 'This discovery call is designed for executives and sales managers committed to scaling their sales. We invest time preparing a personalized analysis for each prospect.',
    'booking.step6.not': 'This call is NOT for you if:',
    'booking.step6.not1': 'You\'re only looking for free advice',
    'booking.step6.not2': 'You\'re not a decision-maker in your company',
    'booking.step6.not3': 'You don\'t have a budget to invest in your growth',
    'booking.step6.not4': 'You\'re not sure you can attend',
    'booking.step6.is': 'This call IS for you if:',
    'booking.step6.is1': 'You want to automate your customer acquisition',
    'booking.step6.is2': 'You\'re ready to invest to scale your business',
    'booking.step6.is3': 'You\'re looking for a proven solution, not theories',
    'booking.step6.is4': 'You\'re a decision-maker ready to act quickly',
    'booking.step6.confirm': 'I confirm my commitment',
    'booking.step6.confirmText': 'I understand that this call is a mutual evaluation and I commit to being present at the scheduled time. I am a decision-maker and ready to invest in my company\'s growth.',
    'booking.step6.submit': 'Confirm my booking',
    'booking.step6.submitting': 'Submitting...',
    'booking.step7.success': 'Booking confirmed!',
    'booking.step7.thanks': 'Thank you',
    'booking.step7.message': 'Your call request has been registered. You will receive a confirmation email shortly.',
    'booking.step7.details': 'Your booking details:',
    'booking.step7.date': 'Preferred date:',
    'booking.step7.email': 'Email:',
    'booking.step7.company': 'Company:',
    'booking.step7.next': 'Next steps',
    'booking.step7.next1': 'We will analyze your profile and needs',
    'booking.step7.next2': 'You will receive a confirmation email with the call link',
    'booking.step7.next3': 'We will prepare a personalized analysis for your company',
    'booking.step7.home': 'Back to home',
    'booking.button.back': 'Back',
    'booking.button.continue': 'Continue',
    'booking.channel.inbound': 'Inbound Marketing',
    'booking.channel.outbound': 'Outbound / Cold Calling',
    'booking.channel.ads': 'Paid advertising',
    'booking.channel.referral': 'Referrals',
    'booking.channel.other': 'Other',
    'booking.select': 'Select',
    'booking.urgent': 'Urgent',
  },
  dar: {
    // Header
    'nav.home': 'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.ai': 'الذكاء الاصطناعي',
    'nav.testimonials': 'الشهادات',
    'nav.contact': 'تواصل',
    
    // Hero
    'hero.title': 'نحوّل الزبائن بلا ضغط، و نخدمو بالنية و الفهم.',
    'hero.subtitle': 'البيع الواعي بالذكاء الاصطناعي و النية الصافية.',
    'hero.cta.primary': 'اكتشف طريقتنا',
    'hero.cta.secondary': 'دير معانا مكالمة مجانية',
    
    // Mission
    'mission.title': 'النية الصافية هي الاستراتيجية.',
    'mission.text': 'عندنا في The Ultimate Closers، كل عملية بيع هي محادثة صادقة. الذكاء الاصطناعي يعزز الفهم، ماشي التلاعب.',
    'mission.value1': 'النية الطيبة',
    'mission.value2': 'الشفافية',
    'mission.value3': 'الاستقلالية',
    'mission.value4': 'التميز',
    
    // Services
    'services.title': 'حلول إنسانية مدعومة بالتكنولوجيا.',
    'services.card1.title': 'البيع على الأداء',
    'services.card1.text': 'تخلص فقط كي توقع.',
    'services.card2.title': 'التدريب و السكريبتات',
    'services.card2.text': 'بيع واعي و أخلاقي.',
    'services.card3.title': 'تحليل الفانل و الذكاء الاصطناعي',
    'services.card3.text': 'تحليل سلوكي و أتمتة.',
    'services.card4.title': 'أتمتة بالذكاء الاصطناعي بالدارجة',
    'services.card4.text': 'ذكاء اصطناعي متدرب على ثقافتك.',
    
    // AI
    'ai.title': 'ذكاء اصطناعي محلي في خدمة نموك.',
    'ai.text': 'الذكاء الاصطناعي ديالنا بالدارجة يفهم عواطفك و ثقافتك و قيمك.',
    'ai.feature1': 'شات بوت متفاهم',
    'ai.feature2': 'CRM ذكي',
    'ai.feature3': 'ذكاء اصطناعي ثقافي',
    
    // Results
    'results.title': 'نتائج قابلة للقياس، و أخلاق غير قابلة للتفاوض.',
    'results.metric1': '+70% نسبة البيع',
    'results.metric2': '0% ضغط',
    'results.metric3': '100% رضا العملاء',
    'results.quote': 'الأخلاق ماشي عائق للنجاح، هي أساسه.',
    'results.author': 'أ. مارج',
    
    // Testimonials
    'testimonials.title': 'وثقوا فينا.',
    'testimonials.card1': 'وقعت ضعف العقود بلا ما نحس روحي كومرسيال.',
    'testimonials.card2': 'خلاو العملية ديالي إنسانية و فعالة.',
    'testimonials.card3': 'خدمتهم راقية و فيها نية.',
    'testimonials.name1': 'صوفيا',
    'testimonials.name2': 'مارك',
    'testimonials.name3': 'ياسمين',
    
    // CTA
    'cta.title': 'جاهز تبدل طريقة البيع تاعك؟',
    'cta.button': 'دير معانا مكالمة مجانية',
    
    // Footer
    'footer.quote': 'الحكمة في البيع، النور في النمو.',
    'footer.legal': 'قانوني',
    
    // Booking
    'booking.back': 'رجع للرئيسية',
    'booking.step1.title': 'دير معانا مكالمة استراتيجية',
    'booking.step1.subtitle': 'هاد المكالمة باش نشوفو واش الأنظمة ديالنا الأخلاقية و الأوتوماتيكية يمكن تتكامل مع النموذج ديالك.',
    'booking.step1.what': 'شنو غادي تلقى',
    'booking.step1.item1': 'تحليل شخصي للعملية التجارية ديالك الحالية',
    'booking.step1.item2': 'استراتيجيات ملموسة باش تأتمت البروسبكتينغ ديالك',
    'booking.step1.item3': 'تقييم التوافق بين الأنظمة ديالنا و الأهداف ديالك',
    'booking.step1.important': 'مهم:',
    'booking.step1.notice': 'هاد المكالمة ماشي نصيحة مجانية. هي تقييم متبادل محجوز للمديرين و المسؤولين التجاريين اللي عازمين يكبّرو المبيعات ديالهم. عافاك جاوب بدقة باش نحضرو تحليل شخصي.',
    'booking.step1.button': 'ابدا الفورمولير',
    'booking.step2.title': 'شكون نتي؟',
    'booking.step2.subtitle': 'يلاه نتعرفو على بعضياتنا',
    'booking.step2.firstName': 'السمية',
    'booking.step2.lastName': 'العائلة',
    'booking.step2.jobTitle': 'البوست',
    'booking.step2.companyName': 'سمية الشركة',
    'booking.step2.companyWebsite': 'الموقع ديال الشركة',
    'booking.step2.companyLinkedin': 'صفحة لينكدإن',
    'booking.step2.email': 'الإيميل المهني',
    'booking.step2.phone': 'التيليفون / واتساب',
    'booking.step3.title': 'الشركة ديالك',
    'booking.step3.subtitle': 'عاونا نفهمو السياق ديالك',
    'booking.step3.industry': 'القطاع',
    'booking.step3.revenue': 'رقم الأعمال السنوي',
    'booking.step3.teamSize': 'حجم الفريق التجاري',
    'booking.step3.channels': 'القنوات الحالية ديال الاكتساب',
    'booking.step3.challenge': 'شنو هو التحدي الرئيسي ديالك دابا؟',
    'booking.step4.title': 'الأهداف ديالك',
    'booking.step4.subtitle': 'شنو كتسنى من هاد المكالمة؟',
    'booking.step4.objective': 'شنو كتمنى تحصل عليه من هاد المكالمة؟',
    'booking.step4.automate': 'أتمتة البروسبكتينغ',
    'booking.step4.automate.desc': 'وضع أنظمة الاكتساب الأوتوماتيكية',
    'booking.step4.train': 'تدريب الكلوزرز ديالي',
    'booking.step4.train.desc': 'تحسين المهارات ديال الفريق التجاري',
    'booking.step4.rethink': 'إعادة التفكير في البايبلاين',
    'booking.step4.rethink.desc': 'تحسين العملية الكاملة ديال البيع',
    'booking.step4.other': 'هدف آخر',
    'booking.step4.other.desc': 'بغيت نهضر على حاجة محددة',
    'booking.step4.aiCrm': 'واش سبق ليك استعملتي نظام كلوزينغ بالذكاء الاصطناعي ولا CRM أوتوماتيكي؟',
    'booking.step4.aiCrm.yes': 'آه، كنستعمل ولا سبق لي استعملت هاد الأدوات',
    'booking.step4.aiCrm.no': 'لا، مازال',
    'booking.step4.aiCrm.progress': 'في طور التطبيق',
    'booking.step4.urgency': 'شحال عندك الاستعجال؟',
    'booking.step4.urgency.week': 'هاد السيمانة',
    'booking.step4.urgency.month': 'في الشهر',
    'booking.step4.urgency.not': 'ماشي أولوية دابا',
    'booking.step5.title': 'التخطيط',
    'booking.step5.subtitle': 'اختار الوقت اللي بغيتي',
    'booking.step5.date': 'التاريخ المفضل',
    'booking.step5.timezone': 'التوقيت',
    'booking.step5.platform': 'المنصة المفضلة',
    'booking.step5.platformQuestion': 'كيفاش بغيتي تنضم لينا؟',
    'booking.step5.notice': 'من بعد التأكيد، غادي تستقبل إيميل تأكيد فيه الرابط ديال المكالمة و إمكانية زيادة الحدث للكالوندرية ديالك.',
    'booking.step6.title': 'المرحلة الأخيرة',
    'booking.step6.subtitle': 'أكد الالتزام ديالك',
    'booking.step6.warning': 'هاد المكالمة محجوزة للمحترفين الجادين',
    'booking.step6.intro': 'هاد المكالمة مصممة للمديرين و المسؤولين التجاريين اللي عازمين يكبّرو المبيعات ديالهم. كنستثمرو الوقت في التحضير ديال تحليل شخصي لكل بروسبكت.',
    'booking.step6.not': 'هاد المكالمة ماشي ليك إلا:',
    'booking.step6.not1': 'كتقلب غير على نصيحة مجانية',
    'booking.step6.not2': 'ماشي صاحب القرار في الشركة ديالك',
    'booking.step6.not3': 'ماعندكش البودجي باش تستثمر في النمو ديالك',
    'booking.step6.not4': 'ماشي متأكد واش غادي تقدر تحضر',
    'booking.step6.is': 'هاد المكالمة ليك إلا:',
    'booking.step6.is1': 'بغيتي تأتمت الاكتساب ديال العملاء',
    'booking.step6.is2': 'واجد باش تستثمر في تكبير البيزنس ديالك',
    'booking.step6.is3': 'كتقلب على حل مجرب، ماشي نظريات',
    'booking.step6.is4': 'صاحب القرار و واجد تتصرف بزربة',
    'booking.step6.confirm': 'كنأكد الالتزام ديالي',
    'booking.step6.confirmText': 'فاهم بلي هاد المكالمة هي تقييم متبادل و كنلتازم نكون حاضر في الوقت المحدد. أنا صاحب القرار و واجد نستثمر في نمو الشركة ديالي.',
    'booking.step6.submit': 'أكد الحجز ديالي',
    'booking.step6.submitting': 'كيتسيفط...',
    'booking.step7.success': 'الحجز متأكد!',
    'booking.step7.thanks': 'شكرا',
    'booking.step7.message': 'الطلب ديال المكالمة تسجل. غادي تستقبل إيميل تأكيد قريبا.',
    'booking.step7.details': 'تفاصيل الحجز ديالك:',
    'booking.step7.date': 'التاريخ المفضل:',
    'booking.step7.email': 'الإيميل:',
    'booking.step7.company': 'الشركة:',
    'booking.step7.next': 'الخطوات الجاية',
    'booking.step7.next1': 'غادي نحللو البروفيل و الاحتياجات ديالك',
    'booking.step7.next2': 'غادي تستقبل إيميل تأكيد فيه الرابط ديال المكالمة',
    'booking.step7.next3': 'غادي نحضرو تحليل شخصي للشركة ديالك',
    'booking.step7.home': 'رجع للرئيسية',
    'booking.button.back': 'رجوع',
    'booking.button.continue': 'كمّل',
    'booking.channel.inbound': 'التسويق الداخلي',
    'booking.channel.outbound': 'المكالمات الباردة',
    'booking.channel.ads': 'الإعلانات المدفوعة',
    'booking.channel.referral': 'التوصيات',
    'booking.channel.other': 'أخرى',
    'booking.select': 'اختار',
    'booking.urgent': 'مستعجل',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.fr] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
